USE [master]
GO

/****** Necessario alterar o nome de [DataBaseNewPoint] para o ambiente especifico, exemplo: [qcmaint_base_muro_update_br] ******/
CREATE DATABASE [DataBaseNewPoint]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'KAIROS_BASE_MURO', FILENAME = N'D:\DBDATA\DATA\PT\DataBaseNewPoint.mdf' , SIZE = 4566016KB , MAXSIZE = UNLIMITED, FILEGROWTH = 524288KB )
 LOG ON 
( NAME = N'KAIROS_BASE_MURO_log', FILENAME = N'E:\DBDATA\LOG\PT\DataBaseNewPoint_log.ldf' , SIZE = 525696KB , MAXSIZE = 2048GB , FILEGROWTH = 524288KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataBaseNewPoint].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataBaseNewPoint] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataBaseNewPoint] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataBaseNewPoint] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DataBaseNewPoint] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [DataBaseNewPoint] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataBaseNewPoint] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DataBaseNewPoint] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DataBaseNewPoint] SET  MULTI_USER 
GO

ALTER DATABASE [DataBaseNewPoint] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataBaseNewPoint] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataBaseNewPoint] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataBaseNewPoint] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DataBaseNewPoint] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DataBaseNewPoint] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DataBaseNewPoint] SET QUERY_STORE = OFF
GO

USE [DataBaseNewPoint]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = ON;
GO

ALTER DATABASE [DataBaseNewPoint] SET  READ_WRITE 
GO


